server:
  port: 8020
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: pass@word1
      
